version: '2'
services:

  kibana:
    build:
      context: kibana/
    container_name: kibana
    volumes:
      - ./kibana/etc/salt:/etc/salt
    environment:
      - "SSLAB=0.1"
    command:
      - /usr/bin/salt-minion
    links:
      - master
    networks:
      - saltOS
  
networks:
  saltOS:
    driver: bridge
